apiVersion: v1
kind: Pod
metadata:
  name: imp-doodle-postgres
spec:
  volumes:
    - name: postgres_data
      hostPath:
        path: ${HOSTPATH}/podman/volumes/postgres
  containers:
    - name: postgres
      image: postgres:17.2-alpine
      envFrom:
        - configMapRef:
            name: imp-doodle-dev
      volumeMounts:
        - mountPath: /var/lib/postgresql/data:Z
          name: postgres_data
          readOnly: false
      ports:
        # 5434, so it runs next to the imp-chat pod (5433)
        - containerPort: 5432
          hostPort: 5434
          protocol: TCP
